### ISSUE TITLE
Store ingest scripts in folders named after institution

### ISSUE THREAD

**Issue by pabloarosado** [owid/walden#61]
[The ingests folder](https://github.com/owid/walden/tree/master/ingests) is growing and, given that is is a crucial piece of the walden/etl ecosystem, it would make sense for it to have a similar structure as the rest of walden/etl, meaning having folders named after institutions.
Walkthrough walden should be adapted accordingly.

**Comment by Marigold** [comment]
Adapting `walkthrough walden`
